<a href="https://colab.research.google.com/github/ravgupta11/Machine-Learning-Deep-Learning-Matrix/blob/main/LinearRegressionWithoutSkilearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

my_data = pd.read_csv('california_housing_train.csv', delimiter=',') #read the data
my_data

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
def normalize(df):
  for col in df.columns[0:8]:
    mx = df[col].max()
    mn = df[col].min()
    df[col] = (df[col] - mn) / (mx - mn)  ## 1 2 3 4 5 6 7 8 9 9 10 (subtract minimum) -> 0 1 2 3 4 5 6 7 8 8 9 > (divide by max size = mx - mn) 0 1/9 2/9 ... 9/9 = 0 1/9 2/9 3/9 ... 1
  return df

def randomize(features, labels, batch):
  c = np.concatenate([features, labels], axis = 1)
  np.random.shuffle(c)
  X = c[:batch, 0:2]
  y = c[:batch, 2].reshape(-1, 1)
  return X, y

def clean_data(my_data): # pandas dataframe
  X = my_data.to_numpy()
  X = X[:, 8].reshape(-1,1) # -1 all rows, 8 means only one column 
  ones = np.ones([X.shape[0], 1]) # create a array containing only ones X.shape[0] rows X.shape[1] columns
  XA = np.concatenate([ones, X],axis=1) # cocatenate the ones to X matrix XA = X augmented
  y = my_data.to_numpy()
  y = y[:, 8].reshape(-1,1) # create the y matrix
  return XA, y

# Summary

>  1) Read the Data .

> 2) Make a column vector from the list.

> 3) Create a array containing ONLY ONES.

> 4) Concate the ones with the column vector (column wise).

> 5) Store the labels in a column vector y.

> 6) Give learning rate (alpha) a value.

> 7) Give iters a value i.e. number of iterations.**





# Summary

> 1) scatter plot the given data (x is feature, y is numerical label)

In [ ]:

def computeCost(X, y, theta):  
    inner = np.power(((X @ theta.T) - y), 2) 
    S = np.sum(inner)
    MSE = S / float(len(X));
    return np.power(MSE, 0.5)

# Summary
> 1) Theta is a column vectors in which weights are having 1, 1 values

> 2) MSE = sum ( (predicted y - real y)^2) / N

> 3) computeCost retuerns the MSE for given weights.

In [ ]:
epsilon = 1e-15 #learning rate
iters = 100000
def gradientDescent(features, labels, theta, epsilon, iters, batch):
    for i in range(iters):
        X, y = randomize(features, labels, batch)
        Diff = (X @ theta.T - y) * X * 2; # * is element wise 
        Diff = np.sum(Diff, axis = 0) / float(batch)# len(X) is number of rows
        theta = theta - (epsilon) * Diff 
        cost = computeCost(X, y, theta)
        if(i % 10000 == 0):
          print(theta, cost)
    return (theta, cost)
  
theta = np.random.rand(1, 2)
my_data = normalize(my_data)
XA, y = clean_data(my_data)
print(XA, y)
batch = 50
theta, cost = gradientDescent(XA, y / 100, theta, epsilon, iters, batch)  
print(theta, cost)

[[1.000e+00 6.690e+04]
 [1.000e+00 8.010e+04]
 [1.000e+00 8.570e+04]
 ...
 [1.000e+00 1.036e+05]
 [1.000e+00 8.580e+04]
 [1.000e+00 9.460e+04]] [[ 66900.]
 [ 80100.]
 [ 85700.]
 ...
 [103600.]
 [ 85800.]
 [ 94600.]]
[[0.36425421 0.43048917]] 95043.03519452493
[[0.36425316 0.14610443]] 30368.54582818366
[[0.36425283 0.05405146]] 10570.803038336975
[[0.36425272 0.02424099]] 3403.46625709229
[[0.36425268 0.01461136]] 1353.797625792695
[[0.36425267 0.01149   ]] 332.2961392743655
[[0.36425267 0.0104808 ]] 119.85980716395161
[[0.36425267 0.01015473]] 44.18543421699967
[[0.36425266 0.010049  ]] 12.317049178279321
[[0.36425266 0.01001489]] 3.5545344851508665
[[0.36425266 0.01000391]] 1.3063380724376439


#Summary

> 1) The gradientDescent function returns (weights, MSE) tuple

> 2) Number of times , weights are going to be improved

> 3) Calculating differentiation of MSE with respect to weights

> 4) Subtracting learning rate * Differential value  from weights

> 5) Repeating the above procedure for iters times

> 6) Increasing the learning rate > 0.005 will exponentially increase the MSE.



In [ ]:
test_data = pd.read_csv('california_housing_test.csv', delimiter = ',')
test_data_normal = normalize(test_data)
XAt, yt = clean_data(test_data_normal)
print(computeCost(XAt, yt / 100, theta))
test_data['predicted_house_value'] = (XAt @ theta.T) * 100
test_data

1.2510330737716038


longitude  latitude  ...  median_house_value  predicted_house_value
0      0.219814  0.513889  ...            344700.0          344871.362960
1      0.606811  0.181624  ...            176500.0          176605.518690
2      0.657379  0.130342  ...            270500.0          270642.316320
3      0.600619  0.134615  ...            330000.0          330165.608437
4      0.465428  0.402778  ...             81700.0           81768.407888
...         ...       ...  ...                 ...                    ...
2995   0.445820  0.198718  ...            225000.0          225124.504701
2996   0.623323  0.160256  ...            237200.0          237329.280564
2997   0.462332  0.399573  ...             62000.0           62060.696044
2998   0.728586  0.164530  ...            162500.0          162600.038191
2999   0.469556  0.198718  ...            500001.0          500233.157735

[3000 rows x 10 columns]

In [ ]:
from matplotlib import pyplot as plt
final_weights = theta
final_weights

array([[0.36425266, 0.01000391]])

# Summary

> 1) Scatter plot the data points

> 2) plot the line with weight1 as slope and weight2 as y intercept